## Chemical Signiture densities
Visualization of category acerage colored by description. a selection on category that changes the measurements on a barplot below.

In [1]:
import pandas as pd
import numpy as np
import altair as alt
import ipywidgets as widgets
from IPython.display import display
import warnings
warnings.filterwarnings('ignore')

# enable correct rendering
alt.renderers.enable('default')

# uses intermediate json files to speed things up
alt.data_transformers.enable('json')


pd.set_option('display.max_columns', None)

In [2]:
chem_data = pd.read_csv('assets/chem_data_merged.csv', index_col=0)
survey_data = pd.read_csv('assets/combined_tables.csv', index_col=0)
print('The size of the chem_data dataframe')
print('columns:', chem_data.shape[1])
print('rows   :', chem_data.shape[0])
display(chem_data.sample(5))
print('The size of the survey_data dataframe')
print('columns:', survey_data.shape[1])
print('rows   :', survey_data.shape[0])
survey_data.sample(5)

The size of the chem_data dataframe
columns: 26
rows   : 284535

,LakeID,LakeStationNo,LakeStationType,Lat,Long,Town,ProjectID,VisitDate,VisitNumber,StartTime,CollectionMethodID,Depth,ActivityCategory,CharacteristicID,Symbol,Result,Calcs,ProjRemark,RemarkCode,DepthStratumCode,year,population,CharacteristicName,UnitCode,SampleFraction,NormResult
172057,MOREY,1,Pelagic,43.9247,-72.1533,FAIRLEE,LayMon,2006-07-06,1,1419.0,Hose,11.0,Reg,CHLA,NaN,4.61,Y,NaN,NaN,NaN,2006,992.0,Chlorophyll-a,ug/l,NaN,0.018346
246582,SUNSET (BRKFLD),1,Pelagic,44.0436,-72.6039,BROOKFIELD,Laymon,1997-07-25,1,1640.0,Secchi,NaN,Reg,SECCHI,NaN,4.00,Y,NaN,NaN,NaN,1997,1187.0,Secchi transparency,m,NaN,0.252692
229050,SOUTH BAY,1,Pelagic,44.9203,-72.2097,NEWPORT CITY,LakeAsmt,2008-10-17,1,1227.0,Hydrolab,2.0,Reg,CHLAPROBE,NaN,7.71,Y,NaN,NaN,NaN,2008,4695.0,Chlorophyll-a (probe),ug/l,NaN,0.051337
57164,CRYSTAL (BARTON),1,Pelagic,44.7328,-72.1533,BARTON,LakeAsmt,2013-08-09,1,1128.0,Hydrolab,27.9,Reg,COND,NaN,104.00,Y,NaN,NaN,NaN,2013,2728.0,Conductivity,umho/cm,NaN,0.009857
71528,ELFIN,1,Pelagic,43.4694,-72.9881,WALLINGFORD,Laymon,1988-06-17,1,1115.0,Hose,7.0,Reg,CHLA,NaN,4.96,Y,NaN,NaN,NaN,1988,2116.0,Chlorophyll-a,ug/l,NaN,0.019763

The size of the survey_data dataframe
columns: 36
rows   : 773

,LakeID,Description,Lat,Long,Town,Shape_Length,Shape_Area,TREE_CANOPY_acres,GRASS_SHRUBS_acres,BARE_SOIL_acres,WATER_acres,BUILDINGS_acres,ROADS_acres,OTHER_PAVED_acres,RAILROADS_acres,Ag_Hay_acres,Ag_Crops_acres,Ag_Pasture_acres,Ag_Total_acres,Imp_Bare_Soil_acres,Imp_Buildings_acres,Imp_Other_Paved_acres,Imp_Road_acres,Imp_Railroad_acres,Imp_Total_acres,Shrub_Shrubs_acres,Shrub_Total_acres,TC_Coniferous_acres,TC_Deciduous_acres,TC_Total_acres,Wet_Emergent_acres,Wet_Forested_acres,Wet_Scrub_Shrub_acres,Wet_Total_acres,from_file,2016_population
592,ROOD,Watershed,44.07672,-72.58721,WILLIAMSTOWN,7975.064193,1.739559e+06,359.363998,65.691629,0.021004,0.690597,0.868389,1.102891,2.116640,0.000000,41.065952,0.000000,0.000000,41.065952,0.020272,0.885148,2.486016,3.144272,0.000000,6.535709,6.541939,6.541939,108.180619,251.583713,359.764332,3.248288,30.983723,1.935866,36.167877,AOIs_ROOD.xlsx,3446.0
326,HORSE,Watershed,44.61690,-72.21080,GREENSBORO,9262.633620,2.107941e+06,468.319079,45.532062,0.034904,3.322265,0.043058,3.534652,0.097545,0.000000,0.000000,0.000000,0.000000,0.000000,0.067911,0.042648,0.116058,5.195567,0.000000,5.422184,0.946536,0.946536,210.794069,258.350785,469.144853,14.288349,77.086939,5.588561,96.963848,AOIs_HORSE.xls,721.0
536,NULHEGAN,Buffer250ftWaterbody,44.79080,-71.81780,BRIGHTON,8970.142225,3.122917e+05,33.302650,40.629684,0.507368,1.776870,0.021313,0.551229,0.126641,0.249452,0.000000,0.000000,0.000000,0.000000,0.533495,0.021688,0.163102,0.578734,0.247859,1.544878,26.699058,26.699058,16.223196,17.177190,33.400386,31.874374,19.646287,7.322879,58.843540,AOIs_NULHEGAN.xlsx,1177.0
134,DANBY,Buffer250ftWaterbody,43.36560,-73.05220,DANBY,6129.120712,2.184645e+05,24.543519,19.117958,0.000000,9.854733,0.091120,0.000000,0.372573,0.000000,4.619009,0.000000,0.000000,4.619009,0.000000,0.092122,0.419195,0.000000,0.000000,0.511316,0.931383,0.931383,9.122424,15.587722,24.710145,18.789974,15.550470,1.912396,36.252840,AOIs_DANBY.xls,1300.0
420,LITTLE (WELLS),Buffer100ftWBFL,43.43384,-73.20497,WELLS,105723.704562,3.073768e+06,394.678701,186.826268,1.467618,161.633172,4.210175,4.953405,5.700712,0.000000,67.774921,2.672151,0.897419,71.344491,1.513427,4.579198,6.554423,8.552785,0.000000,21.199834,26.851697,26.851697,144.506110,251.466239,395.972349,47.063689,99.621999,20.670011,167.355699,AOIs_LITTLEWELLS.xls,1147.0

In [10]:
chem_data_to_merge = chem_data[chem_data['year'] == 2016].drop('population', axis=1)

In [11]:
merged_data = survey_data.merge(chem_data_to_merge, how='left', on=['LakeID', 'Lat', 'Long', 'Town'])
merged_data.dropna(subset=['CharacteristicID'], inplace=True)
print(merged_data.shape)
merged_data.head(10)

(25447, 57)

,LakeID,Description,Lat,Long,Town,Shape_Length,Shape_Area,TREE_CANOPY_acres,GRASS_SHRUBS_acres,BARE_SOIL_acres,WATER_acres,BUILDINGS_acres,ROADS_acres,OTHER_PAVED_acres,RAILROADS_acres,Ag_Hay_acres,Ag_Crops_acres,Ag_Pasture_acres,Ag_Total_acres,Imp_Bare_Soil_acres,Imp_Buildings_acres,Imp_Other_Paved_acres,Imp_Road_acres,Imp_Railroad_acres,Imp_Total_acres,Shrub_Shrubs_acres,Shrub_Total_acres,TC_Coniferous_acres,TC_Deciduous_acres,TC_Total_acres,Wet_Emergent_acres,Wet_Forested_acres,Wet_Scrub_Shrub_acres,Wet_Total_acres,from_file,2016_population,LakeStationNo,LakeStationType,ProjectID,VisitDate,VisitNumber,StartTime,CollectionMethodID,Depth,ActivityCategory,CharacteristicID,Symbol,Result,Calcs,ProjRemark,RemarkCode,DepthStratumCode,year,CharacteristicName,UnitCode,SampleFraction,NormResult
15,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,Secchi,NaN,Reg,SECCHI,NaN,3.500,Y,NaN,B,NaN,2016.0,Secchi transparency,m,NaN,0.221026
16,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,COND,NaN,67.030,Y,NaN,NaN,NaN,2016.0,Conductivity,umho/cm,NaN,0.006353
17,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,Meter,1.0,Reg,COND,NaN,70.900,Y,NaN,NaN,NaN,2016.0,Conductivity,umho/cm,NaN,0.006719
18,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DAL,NaN,14.760,Y,NaN,NaN,NaN,2016.0,Dissolved Aluminum,ug/l,Dissolved,0.019971
19,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DCA,NaN,2.509,Y,NaN,NaN,NaN,2016.0,Dissolved Calcium,mg/l,Dissolved,0.189055
20,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DCL,NaN,12.940,Y,NaN,NaN,NaN,2016.0,Dissolved Chloride,mg/l,Dissolved,0.170286
21,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DK,NaN,0.772,Y,NaN,NaN,NaN,2016.0,Dissolved Potassium,mg/l,Dissolved,0.504762
22,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DMG,NaN,0.702,Y,NaN,NaN,NaN,2016.0,Dissolved Magnesium,mg/l,Dissolved,0.380392
23,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DNA,NaN,8.526,Y,NaN,NaN,NaN,2016.0,Dissolved Sodium,mg/l,Dissolved,0.157066
24,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DNO3,<,0.020,Y,NaN,NaN,NaN,2016.0,Dissolved Nitrate Nitrogen,mg/l,Dissolved,0.018143

In [12]:
cols_for_viz = ['TREE_CANOPY_acres', 'GRASS_SHRUBS_acres', 'BARE_SOIL_acres', 'WATER_acres', 'BUILDINGS_acres',
                'ROADS_acres', 'OTHER_PAVED_acres', 'RAILROADS_acres', 'Ag_Hay_acres', 'Ag_Crops_acres', 
                'Ag_Pasture_acres', 'Ag_Total_acres', 'Imp_Bare_Soil_acres', 'Imp_Buildings_acres', 'Imp_Other_Paved_acres', 
                'Imp_Road_acres', 'Imp_Railroad_acres', 'Imp_Total_acres', 'Shrub_Shrubs_acres', 'Shrub_Total_acres', 
                'TC_Coniferous_acres', 'TC_Deciduous_acres', 'TC_Total_acres', 'Wet_Emergent_acres', 'Wet_Forested_acres', 
                'Wet_Scrub_Shrub_acres', 'Wet_Total_acres', 'CharacteristicID', 'CharacteristicName', 'Result']
df_for_viz = merged_data[cols_for_viz]

In [13]:
df_for_viz.head()

,TREE_CANOPY_acres,GRASS_SHRUBS_acres,BARE_SOIL_acres,WATER_acres,BUILDINGS_acres,ROADS_acres,OTHER_PAVED_acres,RAILROADS_acres,Ag_Hay_acres,Ag_Crops_acres,Ag_Pasture_acres,Ag_Total_acres,Imp_Bare_Soil_acres,Imp_Buildings_acres,Imp_Other_Paved_acres,Imp_Road_acres,Imp_Railroad_acres,Imp_Total_acres,Shrub_Shrubs_acres,Shrub_Total_acres,TC_Coniferous_acres,TC_Deciduous_acres,TC_Total_acres,Wet_Emergent_acres,Wet_Forested_acres,Wet_Scrub_Shrub_acres,Wet_Total_acres,CharacteristicID,CharacteristicName,Result
15,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,SECCHI,Secchi transparency,3.500
16,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,COND,Conductivity,67.030
17,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,COND,Conductivity,70.900
18,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,DAL,Dissolved Aluminum,14.760
19,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,DCA,Dissolved Calcium,2.509

In [39]:
corr_df = pd.DataFrame(index=cols_for_viz[:-3])
for char in df_for_viz['CharacteristicID'].unique():
    df = df_for_viz[df_for_viz['CharacteristicID'] == char]
    df = df.corr()
    df.drop('Result', axis=0, inplace=True)
    df.rename(columns={'Result': char}, inplace=True)
    corr_df[char] = df[char]

# replace all nan values with 0
corr_df.fillna(0, inplace=True)
# drop a column if the entire column is 0
for col in corr_df.columns:
    if corr_df[col].sum() == 0:
        corr_df.drop(col, axis=1, inplace=True)
corr_df = corr_df.reset_index().rename(columns={'index': 'survey_type'})

In [41]:
# melt the data for visualization
corr_df_for_vis = pd.melt(corr_df, id_vars='survey_type', var_name='CharacteristicID', value_name='correlation')
# merge CharacteristicName
corr_df_for_vis = corr_df_for_vis.merge(df_for_viz[['CharacteristicID', 'CharacteristicName']].drop_duplicates(), how='left', on='CharacteristicID')
corr_df_for_vis

,survey_type,CharacteristicID,correlation,CharacteristicName
0,TREE_CANOPY_acres,SECCHI,0.026178,Secchi transparency
1,GRASS_SHRUBS_acres,SECCHI,-0.000850,Secchi transparency
2,BARE_SOIL_acres,SECCHI,0.049620,Secchi transparency
3,WATER_acres,SECCHI,0.021772,Secchi transparency
4,BUILDINGS_acres,SECCHI,0.077560,Secchi transparency
...,...,...,...,...
1021,TC_Total_acres,OMAL,-0.259465,Organic Monomeric Aluminum
1022,Wet_Emergent_acres,OMAL,-0.004195,Organic Monomeric Aluminum
1023,Wet_Forested_acres,OMAL,-0.188080,Organic Monomeric Aluminum
1024,Wet_Scrub_Shrub_acres,OMAL,0.007909,Organic Monomeric Aluminum
1025,Wet_Total_acres,OMAL,-0.184731,Organic Monomeric Aluminum

In [48]:
_0_condition = alt.condition(alt.datum.correlation == 0, alt.value('white'), alt.Color('correlation:Q'))

chart = alt.Chart(corr_df_for_vis).mark_rect().encode(
    x=alt.X('survey_type:N'),
    y=alt.Y('CharacteristicName:N'),
    color=_0_condition,
    tooltip=[alt.Tooltip('CharacteristicName'), alt.Tooltip('CharacteristicID'), alt.Tooltip('survey_type', title='Survey Type'), alt.Tooltip('correlation')]
)
chart

alt.Chart(...)

    x  y   z
0  -5 -5  50
1  -4 -5  41
2  -3 -5  34
3  -2 -5  29
4  -1 -5  26
.. .. ..  ..
95  0  4  16
96  1  4  17
97  2  4  20
98  3  4  25
99  4  4  32

[100 rows x 3 columns]