## Chemical Signiture densities
Visualization of category acerage colored by description. a selection on category that changes the measurements on a barplot below.

In [10]:
import pandas as pd
import numpy as np
import altair as alt
import ipywidgets as widgets
from IPython.display import display
import warnings
warnings.filterwarnings('ignore')

# enable correct rendering
alt.renderers.enable('default')

# uses intermediate json files to speed things up
alt.data_transformers.enable('json')


pd.set_option('display.max_columns', None)

In [11]:
chem_data = pd.read_csv('assets/chem_data_merged.csv', index_col=0)
survey_data = pd.read_csv('assets/combined_tables.csv', index_col=0)
print('The size of the chem_data dataframe')
print('columns:', chem_data.shape[1])
print('rows   :', chem_data.shape[0])
display(chem_data.sample(5))
print('The size of the survey_data dataframe')
print('columns:', survey_data.shape[1])
print('rows   :', survey_data.shape[0])
survey_data.sample(5)

The size of the chem_data dataframe
columns: 26
rows   : 284535

,LakeID,LakeStationNo,LakeStationType,Lat,Long,Town,ProjectID,VisitDate,VisitNumber,StartTime,CollectionMethodID,Depth,ActivityCategory,CharacteristicID,Symbol,Result,Calcs,ProjRemark,RemarkCode,DepthStratumCode,year,population,CharacteristicName,UnitCode,SampleFraction,NormResult
164527,METCALF,1,Pelagic,44.72883,-72.88330,FLETCHER,Laymon,1994-06-12,1,905.0,Hose,6.40,R1,CHLA,NaN,1.30,Y,NaN,NaN,NaN,1994,1044.0,Chlorophyll-a,ug/l,NaN,0.004941
284453,ZACK WOODS,1,Pelagic,44.61106,-72.50256,HYDE PARK,SpringTP,2019-05-09,1,1310.0,Hydrolab,13.07,Reg,PH,NaN,6.91,Y,NaN,NaN,NaN,2019,2961.0,pH,None,NaN,0.485937
237650,ST. CATHERINE,1,Pelagic,43.47125,-73.21375,WELLS,Laymon,2019-08-18,1,1620.0,Hose,10.00,Reg,CHLA,NaN,6.31,Y,NaN,NaN,NaN,2019,1154.0,Chlorophyll-a,ug/l,NaN,0.025231
68964,ECHO (PLYMTH),1,Pelagic,43.47750,-72.70140,PLYMOUTH,SpringTP,1998-04-22,1,1113.0,Hydrolab,22.00,Reg,PH,NaN,6.95,Y,NaN,NaN,NaN,1998,534.0,pH,None,NaN,0.492188
66630,ECHO (CHARTN),1,Pelagic,44.86231,-71.99507,CHARLESTON,SpringTP,2003-05-14,1,1302.0,Hydrolab,3.00,Reg,DO%,NaN,104.40,Y,NaN,NaN,NaN,2003,951.0,Dissolved Oxygen Saturation,%,NaN,0.579035

The size of the survey_data dataframe
columns: 36
rows   : 773

,LakeID,Description,Lat,Long,Town,Shape_Length,Shape_Area,TREE_CANOPY_acres,GRASS_SHRUBS_acres,BARE_SOIL_acres,WATER_acres,BUILDINGS_acres,ROADS_acres,OTHER_PAVED_acres,RAILROADS_acres,Ag_Hay_acres,Ag_Crops_acres,Ag_Pasture_acres,Ag_Total_acres,Imp_Bare_Soil_acres,Imp_Buildings_acres,Imp_Other_Paved_acres,Imp_Road_acres,Imp_Railroad_acres,Imp_Total_acres,Shrub_Shrubs_acres,Shrub_Total_acres,TC_Coniferous_acres,TC_Deciduous_acres,TC_Total_acres,Wet_Emergent_acres,Wet_Forested_acres,Wet_Scrub_Shrub_acres,Wet_Total_acres,from_file,2016_population
283,GROUT,Buffer100ftWBFL,43.04451,-72.94366,STRATTON,8048.753481,1.207514e+05,25.528603,3.040998,0.000000,1.261100,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,16.832402,8.734425,25.566827,0.673407,10.110095,0.021286,10.804787,AOIs_GROUT.xls,206.0
648,SILVER (BARNRD),Flowline100ft,43.72890,-72.60890,BARNARD,21984.360788,6.618899e+05,135.973789,21.124574,0.000000,4.500894,0.324881,1.132420,0.482596,0.0,12.022439,0.000000,0.000000,12.022439,0.000000,0.375655,0.548803,2.312428,0.0,3.236886,0.593752,0.593752,31.985506,104.084412,136.069918,0.485621,10.125998,1.643014,12.254633,AOIs_SILVERBARNRD.xlsx,918.0
747,WILLOUGHBY,Buffer250ftWaterbody,44.74886,-72.06116,WESTMORE,35248.770155,1.325936e+06,232.546191,50.107211,2.348239,9.285341,6.451170,16.727773,10.163985,0.0,0.467635,0.000000,0.000000,0.467635,2.916121,7.305009,12.085215,20.038222,0.0,42.344568,0.122887,0.122887,81.403583,151.668764,233.072346,0.492197,7.550089,0.138419,8.180705,AOIs_WILLOUGHBY.xls,328.0
210,FAIRLEE,Watershed,43.88294,-72.22941,THETFORD,50603.138611,5.030529e+07,10829.864040,1421.133164,16.400050,53.445105,18.748968,43.052795,48.045799,0.0,776.234695,12.308547,1.683897,790.227139,17.177745,20.202026,53.100000,94.158554,0.0,184.638324,134.098025,134.098025,4962.198099,5875.960618,10838.158717,158.709943,603.461208,50.434183,812.605335,AOIs_FAIRLEE.xls,2578.0
713,TILDYS,Flowline100ft,44.64420,-72.20420,GLOVER,8085.132580,2.500346e+05,35.014470,22.785552,0.055722,2.101196,0.157097,1.413997,0.249267,0.0,0.000000,2.019763,0.000000,2.019763,0.090528,0.166810,0.247956,1.466869,0.0,1.972164,0.000000,0.000000,20.180046,14.945042,35.125088,21.394135,6.086230,0.000000,27.480365,AOIs_TILDYS.xlsx,1086.0

In [12]:
chem_data_to_merge = chem_data[chem_data['year'] == 2016].drop('population', axis=1)

In [13]:
merged_data = survey_data.merge(chem_data_to_merge, how='left', on=['LakeID', 'Lat', 'Long', 'Town'])
merged_data.dropna(subset=['CharacteristicID'], inplace=True)
print(merged_data.shape)
merged_data.head(10)

(25447, 57)

,LakeID,Description,Lat,Long,Town,Shape_Length,Shape_Area,TREE_CANOPY_acres,GRASS_SHRUBS_acres,BARE_SOIL_acres,WATER_acres,BUILDINGS_acres,ROADS_acres,OTHER_PAVED_acres,RAILROADS_acres,Ag_Hay_acres,Ag_Crops_acres,Ag_Pasture_acres,Ag_Total_acres,Imp_Bare_Soil_acres,Imp_Buildings_acres,Imp_Other_Paved_acres,Imp_Road_acres,Imp_Railroad_acres,Imp_Total_acres,Shrub_Shrubs_acres,Shrub_Total_acres,TC_Coniferous_acres,TC_Deciduous_acres,TC_Total_acres,Wet_Emergent_acres,Wet_Forested_acres,Wet_Scrub_Shrub_acres,Wet_Total_acres,from_file,2016_population,LakeStationNo,LakeStationType,ProjectID,VisitDate,VisitNumber,StartTime,CollectionMethodID,Depth,ActivityCategory,CharacteristicID,Symbol,Result,Calcs,ProjRemark,RemarkCode,DepthStratumCode,year,CharacteristicName,UnitCode,SampleFraction,NormResult
15,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,Secchi,NaN,Reg,SECCHI,NaN,3.500,Y,NaN,B,NaN,2016.0,Secchi transparency,m,NaN,0.221026
16,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,COND,NaN,67.030,Y,NaN,NaN,NaN,2016.0,Conductivity,umho/cm,NaN,0.006353
17,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,Meter,1.0,Reg,COND,NaN,70.900,Y,NaN,NaN,NaN,2016.0,Conductivity,umho/cm,NaN,0.006719
18,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DAL,NaN,14.760,Y,NaN,NaN,NaN,2016.0,Dissolved Aluminum,ug/l,Dissolved,0.019971
19,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DCA,NaN,2.509,Y,NaN,NaN,NaN,2016.0,Dissolved Calcium,mg/l,Dissolved,0.189055
20,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DCL,NaN,12.940,Y,NaN,NaN,NaN,2016.0,Dissolved Chloride,mg/l,Dissolved,0.170286
21,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DK,NaN,0.772,Y,NaN,NaN,NaN,2016.0,Dissolved Potassium,mg/l,Dissolved,0.504762
22,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DMG,NaN,0.702,Y,NaN,NaN,NaN,2016.0,Dissolved Magnesium,mg/l,Dissolved,0.380392
23,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DNA,NaN,8.526,Y,NaN,NaN,NaN,2016.0,Dissolved Sodium,mg/l,Dissolved,0.157066
24,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DNO3,<,0.020,Y,NaN,NaN,NaN,2016.0,Dissolved Nitrate Nitrogen,mg/l,Dissolved,0.018143

In [14]:
cols_for_viz = ['TREE_CANOPY_acres', 'GRASS_SHRUBS_acres', 'BARE_SOIL_acres', 'WATER_acres', 'BUILDINGS_acres',
                'ROADS_acres', 'OTHER_PAVED_acres', 'RAILROADS_acres', 'Ag_Hay_acres', 'Ag_Crops_acres', 
                'Ag_Pasture_acres', 'Ag_Total_acres', 'Imp_Bare_Soil_acres', 'Imp_Buildings_acres', 'Imp_Other_Paved_acres', 
                'Imp_Road_acres', 'Imp_Railroad_acres', 'Imp_Total_acres', 'Shrub_Shrubs_acres', 'Shrub_Total_acres', 
                'TC_Coniferous_acres', 'TC_Deciduous_acres', 'TC_Total_acres', 'Wet_Emergent_acres', 'Wet_Forested_acres', 
                'Wet_Scrub_Shrub_acres', 'Wet_Total_acres', 'CharacteristicID', 'CharacteristicName', 'NormResult']
df_for_viz = merged_data[cols_for_viz]

In [15]:
df_for_viz.head()

,TREE_CANOPY_acres,GRASS_SHRUBS_acres,BARE_SOIL_acres,WATER_acres,BUILDINGS_acres,ROADS_acres,OTHER_PAVED_acres,RAILROADS_acres,Ag_Hay_acres,Ag_Crops_acres,Ag_Pasture_acres,Ag_Total_acres,Imp_Bare_Soil_acres,Imp_Buildings_acres,Imp_Other_Paved_acres,Imp_Road_acres,Imp_Railroad_acres,Imp_Total_acres,Shrub_Shrubs_acres,Shrub_Total_acres,TC_Coniferous_acres,TC_Deciduous_acres,TC_Total_acres,Wet_Emergent_acres,Wet_Forested_acres,Wet_Scrub_Shrub_acres,Wet_Total_acres,CharacteristicID,CharacteristicName,NormResult
15,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,SECCHI,Secchi transparency,0.221026
16,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,COND,Conductivity,0.006353
17,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,COND,Conductivity,0.006719
18,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,DAL,Dissolved Aluminum,0.019971
19,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,DCA,Dissolved Calcium,0.189055

In [16]:
corr_df = pd.DataFrame(index=cols_for_viz[:-3])
for char in df_for_viz['CharacteristicID'].unique():
    df = df_for_viz[df_for_viz['CharacteristicID'] == char]
    df = df.corr()
    df.drop('NormResult', axis=0, inplace=True)
    df.rename(columns={'NormResult': char}, inplace=True)
    corr_df[char] = df[char]

# replace all nan values with 0
corr_df.fillna(0, inplace=True)
# drop a column if the entire column is 0
for col in corr_df.columns:
    if corr_df[col].sum() == 0:
        corr_df.drop(col, axis=1, inplace=True)
corr_df = corr_df.reset_index().rename(columns={'index': 'survey_type'})

In [17]:
# melt the data for visualization
corr_df_for_vis = pd.melt(corr_df, id_vars='survey_type', var_name='CharacteristicID', value_name='correlation')
# merge CharacteristicName
corr_df_for_vis = corr_df_for_vis.merge(df_for_viz[['CharacteristicID', 'CharacteristicName']].drop_duplicates(), how='left', on='CharacteristicID')
corr_df_for_vis

,survey_type,CharacteristicID,correlation,CharacteristicName
0,TREE_CANOPY_acres,SECCHI,0.026178,Secchi transparency
1,GRASS_SHRUBS_acres,SECCHI,-0.000850,Secchi transparency
2,BARE_SOIL_acres,SECCHI,0.049620,Secchi transparency
3,WATER_acres,SECCHI,0.021772,Secchi transparency
4,BUILDINGS_acres,SECCHI,0.077560,Secchi transparency
...,...,...,...,...
1021,TC_Total_acres,OMAL,-0.259465,Organic Monomeric Aluminum
1022,Wet_Emergent_acres,OMAL,-0.004195,Organic Monomeric Aluminum
1023,Wet_Forested_acres,OMAL,-0.188080,Organic Monomeric Aluminum
1024,Wet_Scrub_Shrub_acres,OMAL,0.007909,Organic Monomeric Aluminum
1025,Wet_Total_acres,OMAL,-0.184731,Organic Monomeric Aluminum

In [18]:
_0_condition = alt.condition(alt.datum.correlation == 0, alt.value('white'), alt.Color('correlation:Q'))

chart = alt.Chart(corr_df_for_vis).mark_rect().encode(
    x=alt.X('survey_type:N'),
    y=alt.Y('CharacteristicName:N'),
    color=_0_condition,
    tooltip=[alt.Tooltip('CharacteristicName'), alt.Tooltip('CharacteristicID'), alt.Tooltip('survey_type', title='Survey Type'), alt.Tooltip('correlation')]
)
chart

alt.Chart(...)