## Chemical Signiture densities
Visualization of category acerage colored by description. a selection on category that changes the measurements on a barplot below.

In [139]:
import pandas as pd
import numpy as np
import altair as alt
import ipywidgets as widgets
from IPython.display import display
import warnings
warnings.filterwarnings('ignore')

# enable correct rendering
alt.renderers.enable('default')

# uses intermediate json files to speed things up
alt.data_transformers.enable('json')


pd.set_option('display.max_columns', None)

In [140]:
chem_data = pd.read_csv('assets/chem_data_merged.csv', index_col=0)
survey_data = pd.read_csv('assets/combined_tables.csv', index_col=0)
print('The size of the chem_data dataframe')
print('columns:', chem_data.shape[1])
print('rows   :', chem_data.shape[0])
display(chem_data.sample(5))
print('The size of the survey_data dataframe')
print('columns:', survey_data.shape[1])
print('rows   :', survey_data.shape[0])
survey_data.sample(5)

The size of the chem_data dataframe
columns: 26
rows   : 284535

,LakeID,LakeStationNo,LakeStationType,Lat,Long,Town,ProjectID,VisitDate,VisitNumber,StartTime,CollectionMethodID,Depth,ActivityCategory,CharacteristicID,Symbol,Result,Calcs,ProjRemark,RemarkCode,DepthStratumCode,year,population,CharacteristicName,UnitCode,SampleFraction,NormResult
215681,SHADOW (GLOVER),1,Pelagic,44.66991,-72.22818,GLOVER,LayMon,2005-08-10,1,1000.0,Hose,15.00,Reg,CHLA,NaN,2.24,Y,NaN,NaN,NaN,2005,1068.0,Chlorophyll-a,ug/l,NaN,0.008748
151215,LONG (GRNSBO),1,Pelagic,44.62591,-72.26272,GREENSBORO,LakeAsmt,2018-08-14,1,829.0,Hydrolab,4.97,Reg,TEMPC,NaN,22.35,Y,Oreo,NaN,NaN,2018,706.0,Temperature,deg C,NaN,0.785461
110687,HARVEYS,1,Pelagic,44.29390,-72.13750,BARNET,Laymon,2002-07-15,1,1210.0,Secchi,NaN,Reg,SECCHI,NaN,4.00,Y,NaN,NaN,NaN,2002,1754.0,Secchi transparency,m,NaN,0.252692
196284,RESCUE,1,Pelagic,43.44940,-72.70080,LUDLOW,LayMon,2007-08-11,1,1040.0,Hose,12.20,Reg,TP,NaN,8.28,Y,NaN,NaN,NaN,2007,2099.0,Total Phosphorus,ug/l,Total,0.003634
160295,MAIDSTONE,1,Pelagic,44.65036,-71.64738,MAIDSTONE,LakeAsmt,2018-08-10,1,1350.0,Hydrolab,3.01,Reg,CHLAPROBE,<,0.03,Y,Oreo,NaN,NaN,2018,199.0,Chlorophyll-a (probe),ug/l,NaN,0.000133

The size of the survey_data dataframe
columns: 36
rows   : 773

,LakeID,Description,Lat,Long,Town,Shape_Length,Shape_Area,TREE_CANOPY_acres,GRASS_SHRUBS_acres,BARE_SOIL_acres,WATER_acres,BUILDINGS_acres,ROADS_acres,OTHER_PAVED_acres,RAILROADS_acres,Ag_Hay_acres,Ag_Crops_acres,Ag_Pasture_acres,Ag_Total_acres,Imp_Bare_Soil_acres,Imp_Buildings_acres,Imp_Other_Paved_acres,Imp_Road_acres,Imp_Railroad_acres,Imp_Total_acres,Shrub_Shrubs_acres,Shrub_Total_acres,TC_Coniferous_acres,TC_Deciduous_acres,TC_Total_acres,Wet_Emergent_acres,Wet_Forested_acres,Wet_Scrub_Shrub_acres,Wet_Total_acres,from_file,2016_population
721,TURTLEHEAD,Buffer250ftWaterbody,44.32523,-72.33105,MARSHFIELD,6657.147863,245115.095312,43.526187,14.494191,0.0,1.809241,0.176865,0.390364,0.169514,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.174920,0.241462,0.834550,0.0,1.250931,2.797608,2.797608,20.629263,23.075595,43.704857,3.269034,16.330403,9.756385,29.355822,AOIs_TURTLEHEAD.xlsx,1524.0
371,KENNY,Buffer250ftWaterbody,42.98890,-72.70610,NEWFANE,3767.947845,130537.877624,30.140818,1.924577,0.0,0.038610,0.088155,0.017915,0.043923,0.0,0.000000,0.010551,0.0,0.010551,0.0,0.130500,0.081381,1.127339,0.0,1.339221,0.000000,0.000000,10.351212,19.816077,30.167289,0.000000,0.934871,0.104992,1.039863,AOIs_KENNY.xls,1645.0
298,HARDWOOD,Buffer100ftWBFL,44.46869,-72.49955,ELMORE,4087.592738,60706.375750,13.001738,1.830060,0.0,0.166055,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,8.790875,4.271826,13.062700,0.629904,7.199961,0.166452,7.996317,AOIs_HARDWOOD.xls,877.0
601,ROUND (MILTON),Buffer250ftWaterbody,44.66530,-73.17780,MILTON,3954.797941,139478.262411,24.068398,9.691643,0.0,0.011367,0.119413,0.271568,0.300541,0.0,4.466857,0.000000,0.0,4.466857,0.0,0.169513,0.330947,0.412259,0.0,0.912719,0.000000,0.000000,12.592595,11.579061,24.171656,0.889934,0.358074,0.000000,1.248008,AOIs_ROUNDMILTON.xlsx,10759.0
519,NICHOLS,Waterbody100ft,44.45670,-72.33830,WOODBURY,8554.819949,129868.884184,29.726979,1.177085,0.0,1.010412,0.096309,0.058996,0.016432,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.119869,0.048770,0.231349,0.0,0.399988,0.000000,0.000000,19.438251,10.334613,29.772863,0.161195,4.200927,0.101752,4.463873,AOIs_NICHOLS.xlsx,886.0

In [141]:
# for this visulaization we need the chem_data from 2016 and the LakeID to merge on, the 'CharacteristicID,
# CharacteristicName, UnitCode, and the Result
chem_data_to_merge = chem_data[((chem_data['year'] <= 2016) & (chem_data['year'] >= 2013))].drop('population', axis=1)
chem_data_to_merge = chem_data_to_merge[['LakeID', 'CharacteristicID', 'CharacteristicName', 'Result']].copy()

# Now we Groupby LakeID as we want one measurement: the mean result of each measurement type per lake.
chem_data_to_merge = chem_data_to_merge.groupby(['LakeID', 'CharacteristicID', 'CharacteristicName']).mean().reset_index()
chem_data_to_merge.sample(10)

               LakeID CharacteristicID   CharacteristicName     Result
713             DANBY              TMG      Total Magnesium  10.500000
234           BIG MUD              TMG      Total Magnesium   0.250000
1466             HOWE              DCA    Dissolved Calcium   1.574500
993      GALE MEADOWS           SECCHI  Secchi transparency   2.700000
2858           RESCUE               TK      Total Potassium   0.696000
4067     WRIGHTSVILLE               PH                   pH   6.241111
3096  SHADOW (GLOVER)              TCL       Total Chloride   2.000000
202               BIG               TK      Total Potassium   0.680000
1686           LAUREL               TP     Total Phosphorus  20.666667
2754          PICKLES               DO     Dissolved Oxygen   9.490000

In [142]:
# Combine the subcategories in the description
cols_from_survey = ['LakeID', 'Description', 'TREE_CANOPY_acres', 'GRASS_SHRUBS_acres', 'BARE_SOIL_acres', 'WATER_acres', 
                    'BUILDINGS_acres','ROADS_acres', 'OTHER_PAVED_acres', 'RAILROADS_acres', 'Ag_Hay_acres', 
                    'Ag_Crops_acres', 'Ag_Pasture_acres', 'Ag_Total_acres', 'Imp_Bare_Soil_acres', 
                    'Imp_Buildings_acres', 'Imp_Other_Paved_acres', 'Imp_Road_acres', 'Imp_Railroad_acres', 
                    'Imp_Total_acres', 'Shrub_Shrubs_acres', 'Shrub_Total_acres', 'TC_Coniferous_acres', 
                    'TC_Deciduous_acres', 'TC_Total_acres', 'Wet_Emergent_acres', 'Wet_Forested_acres', 
                    'Wet_Scrub_Shrub_acres', 'Wet_Total_acres']
# survey_data_grouped = survey_data[cols_from_survey].groupby('LakeID').sum().reset_index()
survey_data_grouped = survey_data[cols_from_survey]
survey_data_grouped.sample(10)

,LakeID,Description,TREE_CANOPY_acres,GRASS_SHRUBS_acres,BARE_SOIL_acres,WATER_acres,BUILDINGS_acres,ROADS_acres,OTHER_PAVED_acres,RAILROADS_acres,Ag_Hay_acres,Ag_Crops_acres,Ag_Pasture_acres,Ag_Total_acres,Imp_Bare_Soil_acres,Imp_Buildings_acres,Imp_Other_Paved_acres,Imp_Road_acres,Imp_Railroad_acres,Imp_Total_acres,Shrub_Shrubs_acres,Shrub_Total_acres,TC_Coniferous_acres,TC_Deciduous_acres,TC_Total_acres,Wet_Emergent_acres,Wet_Forested_acres,Wet_Scrub_Shrub_acres,Wet_Total_acres
310,HARRIMAN (WHITHM),Buffer250ftWaterbody,664.781207,51.509593,19.357773,24.128444,0.578720,8.150635,6.502321,0.0,1.403240,0.0,0.0,1.403240,32.601558,0.593396,7.295025,11.158466,0.0,51.648445,1.834360,1.834360,178.875692,486.640902,665.516594,10.010068,13.655826,0.340378,24.006271
581,RAPONDA,Buffer250ftWaterbody,72.634476,7.850093,0.041637,0.926211,2.491004,2.024655,3.147562,0.0,0.000000,0.0,0.0,0.000000,0.052453,2.836978,4.573716,3.120292,0.0,10.583438,0.000000,0.000000,28.680006,44.142826,72.822832,0.177673,3.561442,0.018771,3.757886
444,LYFORD,Waterbody100ft,9.911320,7.001473,0.146039,0.739894,0.674906,0.000309,0.288557,0.0,0.346739,0.0,0.0,0.346739,0.143128,0.745610,0.313107,0.005280,0.0,1.207125,0.838649,0.838649,7.205302,2.769225,9.974527,1.298901,4.077884,0.852547,6.229332
648,SILVER (BARNRD),Flowline100ft,135.973789,21.124574,0.000000,4.500894,0.324881,1.132420,0.482596,0.0,12.022439,0.0,0.0,12.022439,0.000000,0.375655,0.548803,2.312428,0.0,3.236886,0.593752,0.593752,31.985506,104.084412,136.069918,0.485621,10.125998,1.643014,12.254633
399,LILY (POULTY),Waterbody100ft,7.963947,6.159401,0.000000,0.212819,0.200279,0.104711,0.034656,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.234041,0.032466,0.146972,0.0,0.413478,1.572104,1.572104,5.153623,2.891766,8.045389,1.279516,1.891224,1.746158,4.916898
164,ECHO (CHARTN),Buffer250ftWaterbody,74.084241,40.644757,0.285839,2.018477,2.622896,3.496598,4.893976,0.0,11.435305,0.0,0.0,11.435305,0.341549,2.821280,5.854760,4.583173,0.0,13.600762,0.000000,0.000000,37.354845,37.037071,74.391915,3.680226,21.128735,0.742404,25.551365
564,PERCH (BENSON),Waterbody100ft,12.189443,0.676697,0.004448,0.067213,0.174641,0.186997,0.067398,0.0,0.000000,0.0,0.0,0.000000,0.008272,0.221331,0.089705,0.801286,0.0,1.120594,0.000000,0.000000,9.185554,3.041457,12.227011,0.000000,1.082810,0.000000,1.082810
296,HARDWOOD,Flowline100ft,0.382704,0.040093,0.000000,0.002224,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.376787,0.011031,0.387818,0.000000,0.303626,0.000000,0.303626
187,ELLIGO,Waterbody100ft,36.903031,11.242722,0.101684,2.178169,0.604789,2.639576,1.219896,0.0,0.040581,0.0,0.0,0.040581,0.197277,0.695732,1.463950,3.457380,0.0,5.814339,1.799291,1.799291,18.106165,18.897560,37.003725,3.840132,5.706334,3.690759,13.237225
163,ECHO (CHARTN),Buffer100ftWBFL,504.675700,158.021485,0.860420,177.818550,2.486309,5.871400,6.050119,0.0,67.961500,0.0,0.0,67.961500,1.033193,2.638996,6.653821,7.430658,0.0,17.756668,10.357996,10.357996,215.532652,290.231170,505.763822,49.947719,166.579700,27.376920,243.904339

In [143]:
merged_data = survey_data_grouped.merge(chem_data_to_merge, how='inner', on='LakeID').drop('LakeID', axis=1)
print(merged_data.shape)

(6950, 31)

In [144]:
MEASUREMENT_THREASHOLD = 20
corrs = {}
for desc in merged_data['Description'].unique():
    corr_df = pd.DataFrame(index=merged_data.columns[:-3])
    for char in merged_data['CharacteristicID'].unique():
        df = merged_data[((merged_data['CharacteristicID'] == char) & (merged_data['Description'] == desc))]
        # because we are calculating correlations if there are measuremetns with less than 5 measurements
        #  we will drop them as the correlation wont make sense or will be misleading
        if df.shape[0] < MEASUREMENT_THREASHOLD:
            continue
        else:
            df = df.corr()
            df.drop('Result', axis=0, inplace=True)
            df.rename(columns={'Result': char}, inplace=True)
            corr_df[char] = df[char]

    # replace all nan values with 0
    corr_df.fillna(0, inplace=True)
    # drop a column if the entire column is 0
    for col in corr_df.columns:
        if corr_df[col].sum() == 0:
            corr_df.drop(col, axis=1, inplace=True)
    corr_df.drop('Description', axis=0, inplace=True)
    corr_df = corr_df.reset_index().rename(columns={'index': 'survey_type'})
    
    corrs[desc] = corr_df

In [145]:
for key, cor in corrs.items():
    cor['Description'] = key
    print(key)
    print(cor.shape)

Watershed
(27, 23)
Flowline100ft
(27, 23)
Waterbody100ft
(27, 23)
Buffer100ftWBFL
(27, 23)
Buffer250ftWaterbody
(27, 23)

In [151]:
corrs_final = pd.concat(corrs, axis=0, ignore_index=True)
print(corrs_final.shape)

(135, 23)

,survey_type,CHLA,SECCHI,TP,COND,PH,TEMPC,TOTALHARD,CHLAPROBE,DO,DO%,REGALK,TAL,TCA,TCL,TFE,TK,TMG,TMN,TN,TNA,TURBNTU,Description
62,Ag_Hay_acres,0.366877,-0.200000,0.464844,0.263129,0.330597,-0.026232,0.276392,0.154948,0.232697,0.254240,0.231643,-0.125591,0.205646,0.212759,-0.207285,0.552386,0.282730,0.337269,0.163074,0.245673,0.356239,Waterbody100ft
21,TC_Deciduous_acres,-0.177629,-0.112881,-0.130273,-0.185786,-0.257453,-0.231645,-0.209206,-0.162530,0.226025,0.117182,-0.268778,0.184954,-0.262132,-0.060764,0.305704,-0.077492,-0.178448,-0.122788,-0.067054,-0.032617,0.014200,Watershed
61,RAILROADS_acres,-0.128855,-0.013753,-0.093408,-0.078339,-0.050203,0.107154,-0.103185,-0.052431,-0.117515,-0.015061,-0.102144,0.069763,-0.118986,-0.079435,0.000000,-0.088687,-0.103544,0.000000,-0.054482,-0.097590,-0.076557,Waterbody100ft
74,TC_Coniferous_acres,-0.073572,0.275751,-0.069790,-0.213846,-0.208821,-0.016000,-0.186011,0.065328,-0.155368,-0.234932,-0.240597,-0.011750,-0.248138,-0.243839,0.028345,0.000682,-0.198130,-0.063919,-0.048395,-0.232904,-0.101967,Waterbody100ft
128,TC_Coniferous_acres,-0.025660,0.271859,-0.058165,-0.190763,-0.201513,-0.070890,-0.177644,0.079000,-0.071657,-0.198183,-0.240533,0.032306,-0.240998,-0.202433,0.100782,0.069404,-0.198524,0.000863,-0.041213,-0.178273,-0.106399,Buffer250ftWaterbody
40,Imp_Buildings_acres,-0.100581,-0.055265,-0.084938,-0.099331,-0.115934,-0.178241,-0.117743,-0.123717,0.212829,0.278351,-0.168811,0.120247,-0.155689,0.005514,0.215984,-0.022010,-0.121000,-0.051962,-0.038053,0.031974,-0.044695,Flowline100ft
2,BARE_SOIL_acres,-0.137040,-0.009422,-0.090774,-0.106559,-0.117995,-0.163575,-0.123221,-0.128359,0.251691,0.214192,-0.178660,0.147765,-0.169437,-0.024860,0.259666,-0.014504,-0.138220,-0.098578,-0.066490,0.039658,-0.093783,Watershed
92,Ag_Total_acres,0.139091,-0.088248,0.100963,0.105096,0.052218,-0.042289,0.095910,0.115523,0.256288,0.278503,0.053326,-0.042202,0.054901,0.164600,0.023536,0.404725,0.047678,0.383079,0.121083,0.201762,0.033918,Buffer100ftWBFL
28,GRASS_SHRUBS_acres,-0.005511,-0.091669,-0.008916,-0.046788,-0.121425,-0.135608,-0.063196,-0.035914,0.220121,0.237433,-0.119005,0.080657,-0.113437,0.039551,0.188134,0.081693,-0.076119,0.037353,0.019384,0.042662,0.005951,Flowline100ft
93,Imp_Bare_Soil_acres,-0.155243,-0.065080,-0.095440,-0.131106,-0.171916,-0.173650,-0.146374,-0.106225,0.171548,0.127018,-0.190967,0.141222,-0.184503,-0.030123,0.236673,-0.035814,-0.127779,-0.084186,-0.051403,-0.002687,-0.023867,Buffer100ftWBFL

In [152]:
# melt the data for visualization
corr_df_for_vis = pd.melt(corrs_final, id_vars=['survey_type', 'Description'], var_name='CharacteristicID', value_name='correlation')
# merge CharacteristicName
corr_df_for_vis = corr_df_for_vis.merge(merged_data[['CharacteristicID', 'CharacteristicName']].drop_duplicates(), how='left', on='CharacteristicID')
# lets take the abs value of the corelation column so that we can compare them
# corr_df_for_vis['correlation'] = np.abs(corr_df_for_vis['correlation'])
print(corr_df.shape)
corr_df_for_vis.sample(5)

(27, 23)

,survey_type,Description,CharacteristicID,correlation,CharacteristicName
1410,OTHER_PAVED_acres,Waterbody100ft,REGALK,-0.209322,Alkalinity
1022,Wet_Emergent_acres,Waterbody100ft,CHLAPROBE,0.385597,Chlorophyll-a (probe)
2365,Imp_Railroad_acres,Waterbody100ft,TMN,0.000000,Total Manganese
2387,Ag_Total_acres,Buffer100ftWBFL,TMN,0.383079,Total Manganese
1070,Imp_Total_acres,Buffer250ftWaterbody,CHLAPROBE,-0.154361,Chlorophyll-a (probe)

In [157]:
options = corr_df_for_vis['Description'].unique()
desc_dropdown = alt.binding_select(options=options, name='Description')
desc_condition = alt.selection_single(fields=['Description'], bind=desc_dropdown)

chart = alt.Chart(corr_df_for_vis).mark_rect().encode(
    x=alt.X('survey_type:N', axis=alt.Axis(title='Land use survey category')),
    y=alt.Y('CharacteristicName:N', axis=alt.Axis(title='Measurement Characteristic')),
    color=alt.condition(alt.datum.correlation == 0, alt.value('white'), alt.Color('correlation:Q')),
    tooltip=[alt.Tooltip('CharacteristicName'), alt.Tooltip('CharacteristicID'), alt.Tooltip('survey_type', title='Survey Type'), alt.Tooltip('correlation')]
).add_selection(
    desc_condition
).transform_filter(
    desc_condition
)
display(chart)

['Watershed' 'Flowline100ft' 'Waterbody100ft' 'Buffer100ftWBFL'
 'Buffer250ftWaterbody']

alt.Chart(...)