## Chemical Signiture densities
Visualization of category acerage colored by description. a selection on category that changes the measurements on a barplot below.

In [19]:
import pandas as pd
import numpy as np
import altair as alt
import ipywidgets as widgets
from IPython.display import display
import warnings
warnings.filterwarnings('ignore')

# enable correct rendering
alt.renderers.enable('default')

# uses intermediate json files to speed things up
alt.data_transformers.enable('json')


pd.set_option('display.max_columns', None)

In [20]:
chem_data = pd.read_csv('assets/chem_data_merged.csv', index_col=0)
survey_data = pd.read_csv('assets/combined_tables.csv', index_col=0)
print('The size of the chem_data dataframe')
print('columns:', chem_data.shape[1])
print('rows   :', chem_data.shape[0])
display(chem_data.sample(5))
print('The size of the survey_data dataframe')
print('columns:', survey_data.shape[1])
print('rows   :', survey_data.shape[0])
survey_data.sample(5)

The size of the chem_data dataframe
columns: 26
rows   : 284535

,LakeID,LakeStationNo,LakeStationType,Lat,Long,Town,ProjectID,VisitDate,VisitNumber,StartTime,CollectionMethodID,Depth,ActivityCategory,CharacteristicID,Symbol,Result,Calcs,ProjRemark,RemarkCode,DepthStratumCode,year,population,CharacteristicName,UnitCode,SampleFraction,NormResult
208041,SALEM,1,Pelagic,44.93000,-72.10440,DERBY,SpringTP,2000-05-18,1,1106.0,Hydrolab,9.0,Reg,TEMPC,NaN,11.470,Y,NaN,NaN,NaN,2000,4604.0,Temperature,deg C,NaN,0.399645
23027,BRANCH,1,Pelagic,43.08079,-73.01964,SUNDERLAND,AcidLake,1990-08-01,1,1600.0,PlasticKemm,1.0,Reg,DMG,NaN,0.253,Y,NaN,NaN,E,1990,872.0,Dissolved Magnesium,mg/l,Dissolved,0.086928
282070,WOODWARD,1,Pelagic,43.56500,-72.75970,PLYMOUTH,SpringTP,2004-04-29,1,1316.0,Hydrolab,6.0,Reg,PH,NaN,7.030,Y,NaN,NaN,NaN,2004,590.0,pH,None,NaN,0.504687
205396,RUTLAND CITY,1,Pelagic,43.64890,-72.94340,RUTLAND TOWN,SpringTP,2008-04-22,1,1114.0,Hydrolab,4.0,Reg,DO%,NaN,104.800,Y,NaN,NaN,NaN,2008,4083.0,Dissolved Oxygen Saturation,%,NaN,0.581253
183169,OSMORE,1,Pelagic,44.30830,-72.27890,PEACHAM,AcidLake,1985-05-15,1,1215.0,PlasticKemm,1.0,Reg,DAL,NaN,32.000,Y,NaN,NaN,NaN,1985,NaN,Dissolved Aluminum,ug/l,Dissolved,0.044993

The size of the survey_data dataframe
columns: 36
rows   : 773

,LakeID,Description,Lat,Long,Town,Shape_Length,Shape_Area,TREE_CANOPY_acres,GRASS_SHRUBS_acres,BARE_SOIL_acres,WATER_acres,BUILDINGS_acres,ROADS_acres,OTHER_PAVED_acres,RAILROADS_acres,Ag_Hay_acres,Ag_Crops_acres,Ag_Pasture_acres,Ag_Total_acres,Imp_Bare_Soil_acres,Imp_Buildings_acres,Imp_Other_Paved_acres,Imp_Road_acres,Imp_Railroad_acres,Imp_Total_acres,Shrub_Shrubs_acres,Shrub_Total_acres,TC_Coniferous_acres,TC_Deciduous_acres,TC_Total_acres,Wet_Emergent_acres,Wet_Forested_acres,Wet_Scrub_Shrub_acres,Wet_Total_acres,from_file,2016_population
321,HOLLAND,Watershed,44.98588,-71.92928,HOLLAND,34218.969358,2.122666e+07,4173.599805,225.055388,1.868237,107.125577,1.209826,4.315380,3.010604,0.0,26.556409,0.000000,0.0,26.556409,2.125118,1.328209,3.699084,7.298394,0.0,14.450805,49.533898,49.533898,1586.558591,2589.134115,4175.692706,136.683387,1146.262926,45.153158,1328.099471,AOIs_HOLLAND.xls,608.0
192,ELMORE,Waterbody100ft,44.53470,-72.52560,ELMORE,9995.115913,1.500054e+05,16.485919,14.632631,0.059305,2.077103,1.989010,0.339337,1.476699,0.0,0.029502,0.000000,0.0,0.029502,0.068040,2.200320,1.642755,0.445539,0.0,4.356655,2.552262,2.552262,3.509858,13.160502,16.670360,1.951737,1.546664,3.255509,6.753911,AOIs_ELMORE.xls,877.0
445,LYFORD,Buffer100ftWBFL,44.44499,-72.25037,WALDEN,5064.992940,7.593723e+04,9.911876,7.001658,0.146039,0.739894,0.674906,0.000309,0.288557,0.0,0.346739,0.000000,0.0,0.346739,0.143128,0.745610,0.313107,0.005280,0.0,1.207125,0.838649,0.838649,7.205321,2.769655,9.974975,1.298901,4.077884,0.853166,6.229951,AOIs_LYFORD.xls,938.0
715,TILDYS,Buffer100ftWBFL,44.64420,-72.20420,GLOVER,11004.908926,2.956617e+05,40.581498,25.907415,0.140665,3.562636,0.201947,2.407544,0.249267,0.0,0.000000,3.099193,0.0,3.099193,0.175251,0.223495,0.247956,2.660940,0.0,3.307641,0.000000,0.000000,22.478016,18.215468,40.693485,23.210862,6.851130,0.000000,30.061992,AOIs_TILDYS.xlsx,1086.0
394,LILY (LONDRY),Waterbody100ft,43.23470,-72.75170,LONDONDERRY,4132.266507,6.160540e+04,13.384689,0.695971,0.045406,1.095231,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.091636,0.000000,0.000000,0.000000,0.0,0.091636,0.000000,0.000000,11.448628,1.964378,13.413007,0.139151,4.079125,0.408547,4.626823,AOIs_LILYLONDRY.xls,1712.0

In [21]:
chem_data_to_merge = chem_data[chem_data['year'] == 2016].drop('population', axis=1)

In [22]:
merged_data = survey_data.merge(chem_data_to_merge, how='left', on=['LakeID', 'Lat', 'Long', 'Town'])
merged_data.dropna(subset=['CharacteristicID'], inplace=True)
print(merged_data.shape)
merged_data.head(10)

(25447, 57)

,LakeID,Description,Lat,Long,Town,Shape_Length,Shape_Area,TREE_CANOPY_acres,GRASS_SHRUBS_acres,BARE_SOIL_acres,WATER_acres,BUILDINGS_acres,ROADS_acres,OTHER_PAVED_acres,RAILROADS_acres,Ag_Hay_acres,Ag_Crops_acres,Ag_Pasture_acres,Ag_Total_acres,Imp_Bare_Soil_acres,Imp_Buildings_acres,Imp_Other_Paved_acres,Imp_Road_acres,Imp_Railroad_acres,Imp_Total_acres,Shrub_Shrubs_acres,Shrub_Total_acres,TC_Coniferous_acres,TC_Deciduous_acres,TC_Total_acres,Wet_Emergent_acres,Wet_Forested_acres,Wet_Scrub_Shrub_acres,Wet_Total_acres,from_file,2016_population,LakeStationNo,LakeStationType,ProjectID,VisitDate,VisitNumber,StartTime,CollectionMethodID,Depth,ActivityCategory,CharacteristicID,Symbol,Result,Calcs,ProjRemark,RemarkCode,DepthStratumCode,year,CharacteristicName,UnitCode,SampleFraction,NormResult
15,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,Secchi,NaN,Reg,SECCHI,NaN,3.500,Y,NaN,B,NaN,2016.0,Secchi transparency,m,NaN,0.221026
16,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,COND,NaN,67.030,Y,NaN,NaN,NaN,2016.0,Conductivity,umho/cm,NaN,0.006353
17,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,Meter,1.0,Reg,COND,NaN,70.900,Y,NaN,NaN,NaN,2016.0,Conductivity,umho/cm,NaN,0.006719
18,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DAL,NaN,14.760,Y,NaN,NaN,NaN,2016.0,Dissolved Aluminum,ug/l,Dissolved,0.019971
19,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DCA,NaN,2.509,Y,NaN,NaN,NaN,2016.0,Dissolved Calcium,mg/l,Dissolved,0.189055
20,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DCL,NaN,12.940,Y,NaN,NaN,NaN,2016.0,Dissolved Chloride,mg/l,Dissolved,0.170286
21,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DK,NaN,0.772,Y,NaN,NaN,NaN,2016.0,Dissolved Potassium,mg/l,Dissolved,0.504762
22,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DMG,NaN,0.702,Y,NaN,NaN,NaN,2016.0,Dissolved Magnesium,mg/l,Dissolved,0.380392
23,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DNA,NaN,8.526,Y,NaN,NaN,NaN,2016.0,Dissolved Sodium,mg/l,Dissolved,0.157066
24,ATHENS,Watershed,43.1225,-72.6056,ATHENS,6798.212161,1.378627e+06,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,AOIs_ATHENS.xls,438.0,1.0,Pelagic,AcidMisc,2016-04-20,1.0,1052.0,PlasticKemm,1.0,Reg,DNO3,<,0.020,Y,NaN,NaN,NaN,2016.0,Dissolved Nitrate Nitrogen,mg/l,Dissolved,0.018143

In [23]:
cols_for_viz = ['TREE_CANOPY_acres', 'GRASS_SHRUBS_acres', 'BARE_SOIL_acres', 'WATER_acres', 'BUILDINGS_acres',
                'ROADS_acres', 'OTHER_PAVED_acres', 'RAILROADS_acres', 'Ag_Hay_acres', 'Ag_Crops_acres', 
                'Ag_Pasture_acres', 'Ag_Total_acres', 'Imp_Bare_Soil_acres', 'Imp_Buildings_acres', 'Imp_Other_Paved_acres', 
                'Imp_Road_acres', 'Imp_Railroad_acres', 'Imp_Total_acres', 'Shrub_Shrubs_acres', 'Shrub_Total_acres', 
                'TC_Coniferous_acres', 'TC_Deciduous_acres', 'TC_Total_acres', 'Wet_Emergent_acres', 'Wet_Forested_acres', 
                'Wet_Scrub_Shrub_acres', 'Wet_Total_acres', 'CharacteristicID', 'CharacteristicName', 'NormResult']
df_for_viz = merged_data[cols_for_viz]

In [24]:
df_for_viz.head()

,TREE_CANOPY_acres,GRASS_SHRUBS_acres,BARE_SOIL_acres,WATER_acres,BUILDINGS_acres,ROADS_acres,OTHER_PAVED_acres,RAILROADS_acres,Ag_Hay_acres,Ag_Crops_acres,Ag_Pasture_acres,Ag_Total_acres,Imp_Bare_Soil_acres,Imp_Buildings_acres,Imp_Other_Paved_acres,Imp_Road_acres,Imp_Railroad_acres,Imp_Total_acres,Shrub_Shrubs_acres,Shrub_Total_acres,TC_Coniferous_acres,TC_Deciduous_acres,TC_Total_acres,Wet_Emergent_acres,Wet_Forested_acres,Wet_Scrub_Shrub_acres,Wet_Total_acres,CharacteristicID,CharacteristicName,NormResult
15,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,SECCHI,Secchi transparency,0.221026
16,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,COND,Conductivity,0.006353
17,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,COND,Conductivity,0.006719
18,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,DAL,Dissolved Aluminum,0.019971
19,326.232407,10.307862,0.40309,2.056964,0.098966,0.937887,0.630118,0.0,0.0,0.0,0.0,0.0,0.403114,0.099947,0.889489,1.893587,0.0,3.286137,0.0,0.0,62.637475,263.741268,326.378743,2.136629,22.967114,1.199417,26.303159,DCA,Dissolved Calcium,0.189055

In [25]:
corr_df = pd.DataFrame(index=cols_for_viz[:-3])
for char in df_for_viz['CharacteristicID'].unique():
    df = df_for_viz[df_for_viz['CharacteristicID'] == char]
    df = df.corr()
    df.drop('NormResult', axis=0, inplace=True)
    df.rename(columns={'NormResult': char}, inplace=True)
    corr_df[char] = df[char]

# replace all nan values with 0
corr_df.fillna(0, inplace=True)
# drop a column if the entire column is 0
for col in corr_df.columns:
    if corr_df[col].sum() == 0:
        corr_df.drop(col, axis=1, inplace=True)
corr_df = corr_df.reset_index().rename(columns={'index': 'survey_type'})

In [26]:
# melt the data for visualization
corr_df_for_vis = pd.melt(corr_df, id_vars='survey_type', var_name='CharacteristicID', value_name='correlation')
# merge CharacteristicName
corr_df_for_vis = corr_df_for_vis.merge(df_for_viz[['CharacteristicID', 'CharacteristicName']].drop_duplicates(), how='left', on='CharacteristicID')
corr_df_for_vis

,survey_type,CharacteristicID,correlation,CharacteristicName
0,TREE_CANOPY_acres,SECCHI,0.026178,Secchi transparency
1,GRASS_SHRUBS_acres,SECCHI,-0.000850,Secchi transparency
2,BARE_SOIL_acres,SECCHI,0.049620,Secchi transparency
3,WATER_acres,SECCHI,0.021772,Secchi transparency
4,BUILDINGS_acres,SECCHI,0.077560,Secchi transparency
...,...,...,...,...
1021,TC_Total_acres,OMAL,-0.259465,Organic Monomeric Aluminum
1022,Wet_Emergent_acres,OMAL,-0.004195,Organic Monomeric Aluminum
1023,Wet_Forested_acres,OMAL,-0.188080,Organic Monomeric Aluminum
1024,Wet_Scrub_Shrub_acres,OMAL,0.007909,Organic Monomeric Aluminum
1025,Wet_Total_acres,OMAL,-0.184731,Organic Monomeric Aluminum

In [28]:
_0_condition = alt.condition(alt.datum.correlation == 0, alt.value('white'), alt.Color('correlation:Q'))

chart = alt.Chart(corr_df_for_vis).mark_rect().encode(
    x=alt.X('survey_type:N'),
    y=alt.Y('CharacteristicName:N'),
    color=_0_condition,
    tooltip=[alt.Tooltip('CharacteristicName'), alt.Tooltip('CharacteristicID'), alt.Tooltip('survey_type', title='Survey Type'), alt.Tooltip('correlation')]
)
display(chart)

alt.Chart(...)